-- Boafo GH Database Schema (PostgreSQL)
CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(150) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'admin', created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE categories (id SERIAL PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, icon VARCHAR(50), created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE artisans (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(150) UNIQUE NOT NULL, phone VARCHAR(20), password_hash VARCHAR(255) NOT NULL, category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL, bio TEXT, experience_yrs INTEGER DEFAULT 0, location VARCHAR(150), service_areas TEXT, price_min NUMERIC(10,2), price_max NUMERIC(10,2), availability VARCHAR(100), certifications TEXT, profile_photo VARCHAR(255), is_verified BOOLEAN DEFAULT FALSE, is_active BOOLEAN DEFAULT TRUE, avg_rating NUMERIC(3,2) DEFAULT 0.00, total_reviews INTEGER DEFAULT 0, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE portfolio_images (id SERIAL PRIMARY KEY, artisan_id INTEGER NOT NULL REFERENCES artisans(id) ON DELETE CASCADE, url VARCHAR(255) NOT NULL, caption TEXT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE customers (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(150) UNIQUE NOT NULL, phone VARCHAR(20), password_hash VARCHAR(255) NOT NULL, location VARCHAR(150), created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE jobs (id SERIAL PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE, category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL, title VARCHAR(200) NOT NULL, description TEXT, location VARCHAR(150), budget_min NUMERIC(10,2), budget_max NUMERIC(10,2), status VARCHAR(20) DEFAULT 'open', created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE job_applications (id SERIAL PRIMARY KEY, job_id INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, artisan_id INTEGER NOT NULL REFERENCES artisans(id) ON DELETE CASCADE, quote NUMERIC(10,2), message TEXT, status VARCHAR(20) DEFAULT 'pending', created_at TIMESTAMP DEFAULT NOW(), UNIQUE(job_id, artisan_id));
CREATE TABLE messages (id SERIAL PRIMARY KEY, job_id INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, sender_type VARCHAR(10) NOT NULL, sender_id INTEGER NOT NULL, content TEXT NOT NULL, sent_at TIMESTAMP DEFAULT NOW());
CREATE TABLE reviews (id SERIAL PRIMARY KEY, artisan_id INTEGER NOT NULL REFERENCES artisans(id) ON DELETE CASCADE, customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE, job_id INTEGER REFERENCES jobs(id) ON DELETE SET NULL, rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5), comment TEXT, created_at TIMESTAMP DEFAULT NOW(), UNIQUE(artisan_id, customer_id, job_id));
CREATE TABLE notifications (id SERIAL PRIMARY KEY, recipient_type VARCHAR(10) NOT NULL, recipient_id INTEGER NOT NULL, type VARCHAR(50) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT NOW());
CREATE INDEX idx_artisans_category ON artisans(category_id);
CREATE INDEX idx_artisans_verified ON artisans(is_verified);
CREATE INDEX idx_jobs_status ON jobs(status);
CREATE INDEX idx_reviews_artisan ON reviews(artisan_id);
INSERT INTO categories (name, icon) VALUES ('Electrician','⚡'),('Plumber','🔧'),('Carpenter','🪚'),('Mason','🧱'),('Tailor','🧵'),('Painter','🖌️'),('Welder','🔥'),('AC Technician','❄️'),('Tiler','🏠'),('Auto Mechanic','🚗'),('Barber','✂️'),('Gardener','🌱');
