const pool=require('../config/db');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const{sendEmail}=require('../utils/mailer');
function signToken(p){return jwt.sign(p,process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN});}
exports.registerArtisan=async(req,res)=>{try{const{name,email,password,phone,category_id,location}=req.body;if(!name||!email||!password)return res.status(400).json({error:'name, email and password required'});const ex=await pool.query('SELECT id FROM artisans WHERE email=$1',[email]);if(ex.rows.length)return res.status(409).json({error:'Email already registered'});const hash=await bcrypt.hash(password,10);const r=await pool.query('INSERT INTO artisans(name,email,password_hash,phone,category_id,location)VALUES($1,$2,$3,$4,$5,$6)RETURNING id,name,email,is_verified',[name,email,hash,phone||null,category_id||null,location||null]);const a=r.rows[0];sendEmail(email,'welcome_artisan',name);const token=signToken({id:a.id,role:'artisan',name:a.name});res.status(201).json({token,artisan:a});}catch(err){console.error(err);res.status(500).json({error:'Server error'});}};
exports.loginArtisan=async(req,res)=>{try{const{email,password}=req.body;const r=await pool.query('SELECT * FROM artisans WHERE email=$1',[email]);const a=r.rows[0];if(!a)return res.status(401).json({error:'Invalid credentials'});const m=await bcrypt.compare(password,a.password_hash);if(!m)return res.status(401).json({error:'Invalid credentials'});const token=signToken({id:a.id,role:'artisan',name:a.name});res.json({token,artisan:{id:a.id,name:a.name,email:a.email,is_verified:a.is_verified}});}catch(err){console.error(err);res.status(500).json({error:'Server error'});}};
exports.registerCustomer=async(req,res)=>{try{const{name,email,password,phone,location}=req.body;if(!name||!email||!password)return res.status(400).json({error:'name, email and password required'});const ex=await pool.query('SELECT id FROM customers WHERE email=$1',[email]);if(ex.rows.length)return res.status(409).json({error:'Email already registered'});const hash=await bcrypt.hash(password,10);const r=await pool.query('INSERT INTO customers(name,email,password_hash,phone,location)VALUES($1,$2,$3,$4,$5)RETURNING id,name,email',[name,email,hash,phone||null,location||null]);const c=r.rows[0];sendEmail(email,'welcome_customer',name);const token=signToken({id:c.id,role:'customer',name:c.name});res.status(201).json({token,customer:c});}catch(err){console.error(err);res.status(500).json({error:'Server error'});}};
exports.loginCustomer=async(req,res)=>{try{const{email,password}=req.body;const r=await pool.query('SELECT * FROM customers WHERE email=$1',[email]);const c=r.rows[0];if(!c)return res.status(401).json({error:'Invalid credentials'});const m=await bcrypt.compare(password,c.password_hash);if(!m)return res.status(401).json({error:'Invalid credentials'});const token=signToken({id:c.id,role:'customer',name:c.name});res.json({token,customer:{id:c.id,name:c.name,email:c.email}});}catch(err){console.error(err);res.status(500).json({error:'Server error'});}};
exports.registerAdmin=async(req,res)=>{try{const{name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'All fields required'});const ex=await pool.query('SELECT id FROM users WHERE email=$1',[email]);if(ex.rows.length)return res.status(409).json({error:'Email already registered'});const hash=await bcrypt.hash(password,10);const r=await pool.query('INSERT INTO users(name,email,password_hash)VALUES($1,$2,$3)RETURNING id,name,email,role',[name,email,hash]);const u=r.rows[0];const token=signToken({id:u.id,role:'admin',name:u.name});res.status(201).json({token,user:u});}catch(err){console.error(err);res.status(500).json({error:'Server error'});}};
exports.loginAdmin=async(req,res)=>{try{const{email,password}=req.body;const r=await pool.query('SELECT * FROM users WHERE email=$1',[email]);const u=r.rows[0];if(!u)return res.status(401).json({error:'Invalid credentials'});const m=await bcrypt.compare(password,u.password_hash);if(!m)return res.status(401).json({error:'Invalid credentials'});const token=signToken({id:u.id,role:'admin',name:u.name});res.json({token,user:{id:u.id,name:u.name,email:u.email,role:u.role}});}catch(err){console.error(err);res.status(500).json({error:'Server error'});}};
exports.getMe=async(req,res)=>{try{const{id,role}=req.user;let r;if(role==='artisan')r=await pool.query('SELECT a.*,c.name AS category_name FROM artisans a LEFT JOIN categories c ON a.category_id=c.id WHERE a.id=$1',[id]);else if(role==='customer')r=await pool.query('SELECT id,name,email,phone,location,created_at FROM customers WHERE id=$1',[id]);else r=await pool.query('SELECT id,name,email,role,created_at FROM users WHERE id=$1',[id]);const user=r.rows[0];if(user&&user.password_hash)delete user.password_hash;res.json(user);}catch(err){console.error(err);res.status(500).json({error:'Server error'});}};
